\include{00_preamble}

\begin{document}

<<label=setup, echo=FALSE, message=FALSE, warning=FALSE>>=
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 6,
  fig.height = 4,
  fig.align = "center",
  fig.pos = "!htb",
  fig.path = file.path(getwd(), "figures")
)
@

% \include only for texlab. Harmless but remove for final compilation
\include{2_main.Rnw} 
<<child='2_main.Rnw', eval=TRUE>>=
@

\include{3_appendix1.Rnw}
<<child='3_appendix1.Rnw', eval=TRUE>>=
@

\include{4_appendix2.Rnw}
<<child='4_appendix2.Rnw', eval=TRUE>>=
@


\end{document}
