\input{00_preamble}
\addbibresource{/home/urtzi/Documents/zotero.bib}

\newif\iftexlab
\iftexlab
  \input{2_main.Rnw}
  \input{3_appendix1.Rnw}
  \input{4_appendix2.Rnw}
\fi

\begin{document}

<<setup, include=FALSE>>=
library(knitrmini)
opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 6,
  fig.height = 4,
  fig.align = "center",
  fig.pos = "!htb",
  fig.path = file.path(getwd(), "figures/")
)
@

<<child='2_main.Rnw', eval=TRUE>>=
@

<<child='3_appendix1.Rnw', eval=TRUE>>=
@

<<child='4_appendix2.Rnw', eval=TRUE>>=
@

\end{document}
